# -*- coding: utf-8 -*-
"""PINN_SPY_Put_Americana_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxBvTQdmdRxv6skkNeYiZlL4C6hYLLQ1

# PINN para Valuación de Put Americana sobre el SPY
**Reto Bourbaki Finanzas — MA2008B — TEC Campus Estado de México**

Ángel Matías Jácome Olivares A01800569

Alean Reynoso Rangel A01800849

Ximena Lamperero García A01751331

---
## Formulación del problema

El precio $V(S,t)$ de una put americana satisface el problema de frontera libre:

$$\frac{\partial V}{\partial t} + \frac{1}{2}\sigma^2 S^2 \frac{\partial^2 V}{\partial S^2} + rS\frac{\partial V}{\partial S} - rV = 0, \quad S > B(t)$$

Con condiciones:
- **Terminal:** $V(S,T) = \max(K-S,\,0)$
- **Dirichlet:** $V(B(t),t) = K - B(t)$
- **Neumann (smooth-pasting):** $\partial_S V(B(t),t) = -1$
- **Superior:** $V(S_{max},t) = 0$
- **Frontera terminal:** $B(T) = K$

Donde $B(t)$ es la **frontera óptima de ejercicio** — desconocida a priori.

**Referencias:** Song et al. (2024) *Scientific Reports* 14:25289 · Wang & Perdikaris (2021) *J. Comput. Phys.* 428.

## Sección 0 — Imports
"""

!pip install yfinance scipy --quiet

import numpy as np
import torch, torch.nn as nn, torch.optim as optim
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from mpl_toolkits.mplot3d import Axes3D
import yfinance as yf
from scipy.stats import norm
import warnings; warnings.filterwarnings('ignore')

torch.manual_seed(42); np.random.seed(42)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Dispositivo: {device}  |  PyTorch: {torch.__version__}')

"""## Sección 1 — Datos del SPY y parámetros

| Variable | Fuente | Justificación |
|---|---|---|
| `sigma` | SPY jul–dic 2025 (semestre completo) | Más observaciones → estimador más estable |
| `S0` | Primer día del contrato (1-jul-2025) | Precio al inicio |
| `K` | `round(S0)` | Strike ATM |
| `T` | `60/365` | Contrato de 60 días calendario |
| `r` | 0.0425 | Fed Funds jul-2025 |
"""

FECHA_INICIO_DATOS    = '2025-07-01'
FECHA_FIN_DATOS       = '2025-12-31'
FECHA_INICIO_CONTRATO = '2025-07-01'
FECHA_FIN_CONTRATO    = '2025-09-01'

spy_completo = yf.download('SPY', start=FECHA_INICIO_DATOS, end=FECHA_FIN_DATOS,
                            progress=False, auto_adjust=True)
spy_contrato = yf.download('SPY', start=FECHA_INICIO_CONTRATO, end=FECHA_FIN_CONTRATO,
                            progress=False, auto_adjust=True)

# Aplanar multi-índice
close_completo = spy_completo['Close']
close_contrato = spy_contrato['Close']
if hasattr(close_completo, 'columns'): close_completo = close_completo.iloc[:, 0]
if hasattr(close_contrato, 'columns'): close_contrato = close_contrato.iloc[:, 0]

log_ret = np.log(close_completo / close_completo.shift(1)).dropna()
sigma   = float(log_ret.std() * np.sqrt(252))   # vol. con semestre completo
S0      = float(close_contrato.iloc[0])          # precio 1-jul-2025

K    = round(S0)      # strike ATM
r    = 0.0425         # tasa libre de riesgo
T    = 60 / 365       # vencimiento 60 días
Smax = 1.5 * K

S_final_real   = float(close_contrato.iloc[-1])
precios_reales = close_contrato.values.flatten()
fechas_reales  = close_contrato.index

print(f'sigma (jul-dic): {sigma*100:.2f}%  |  S0: ${S0:.2f}  |  K: ${K}')
print(f'r: {r*100:.2f}%  |  T: {T:.4f}a = 60 días  |  Smax: ${Smax:.0f}')
print(f'Días semestre: {len(spy_completo)}  |  Días contrato: {len(spy_contrato)}')
print(f'S_T (29-ago-2025): ${S_final_real:.2f}  ({((S_final_real/S0)-1)*100:+.2f}%)')
print(f'Payoff real: ${max(K-S_final_real,0):.2f}')

"""## Sección 2 — Árbol Binomial CRR y Black-Scholes europeo (referencias)"""

def american_put_binomial(S, K, r, sigma, T, N=1000):
    dt = T/N; u = np.exp(sigma*np.sqrt(dt)); d = 1/u
    p = (np.exp(r*dt)-d)/(u-d); disc = np.exp(-r*dt)
    j = np.arange(N+1)
    V = np.maximum(K - S*(u**(N-2*j)), 0.0)
    for i in range(N-1,-1,-1):
        j = np.arange(i+1); S_i = S*(u**(i-2*j))
        V = np.maximum(disc*(p*V[:-1]+(1-p)*V[1:]), np.maximum(K-S_i,0))
    return float(V[0])

def binomial_boundary(S0, K, r, sigma, T, N=300):
    dt=T/N; u=np.exp(sigma*np.sqrt(dt)); d=1/u
    p=(np.exp(r*dt)-d)/(u-d); disc=np.exp(-r*dt)
    S_tree=np.zeros((N+1,N+1))
    for i in range(N+1):
        for j in range(i+1): S_tree[j,i]=S0*(u**(i-j))*(d**j)
    V_tree=np.zeros((N+1,N+1))
    for j in range(N+1): V_tree[j,N]=max(K-S_tree[j,N],0)
    B=np.zeros(N+1); B[N]=K
    for i in range(N-1,-1,-1):
        B_i=0
        for j in range(i+1):
            hold=disc*(p*V_tree[j,i+1]+(1-p)*V_tree[j+1,i+1])
            intr=max(K-S_tree[j,i],0)
            V_tree[j,i]=max(hold,intr)
            if intr>0 and V_tree[j,i]<=intr+1e-8 and S_tree[j,i]>B_i:
                B_i=S_tree[j,i]
        B[i]=B_i if B_i>0 else B[i+1]
    return np.linspace(0,T,N+1), B

def bs_european_put(S, K, r, sigma, tau):
    tau = np.maximum(tau, 1e-8)
    d1  = (np.log(S/K)+(r+0.5*sigma**2)*tau)/(sigma*np.sqrt(tau))
    return K*np.exp(-r*tau)*norm.cdf(-(d1-sigma*np.sqrt(tau)))-S*norm.cdf(-d1)

# Convergencia binomial (N=1000 como referencia principal)
print('Convergencia árbol binomial:')
for N in [50,100,300,500,1000]:
    print(f'  N={N:5d} → ${american_put_binomial(S0,K,r,sigma,T,N=N):.6f}')

precio_binomial = american_put_binomial(S0, K, r, sigma, T, N=1000)
t1,B1 = binomial_boundary(S0,K,r,sigma,T,N=300)
t2,B2 = binomial_boundary(S0,K,r,sigma,T,N=301)
B_bin = (B1+np.interp(t1,t2,B2))/2; t_bin=t1

print(f'\nPrecio put americana (N=1000): ${precio_binomial:.4f}')
print(f'B(0)=${B_bin[0]:.2f}  B(T)=${B_bin[-1]:.2f}')
print(f'Put europea BS en S0: ${bs_european_put(S0,K,r,sigma,T):.4f}')

"""## Sección 3 — Arquitectura de la PINN

**Correcciones clave respecto a implementaciones naive:**
- Salida lineal en `PriceNet` (sin `Softplus`) → gradientes correctos para Neumann
- `BoundNet` inicializada con sesgo positivo → $B \approx K$ al inicio
- `detach()` de $B$ antes del gradiente Neumann → $\partial_S V$ correcto
"""

S_SCALE = float(K); T_SCALE = float(T)

class PriceNet(nn.Module):
    def __init__(self, hidden=64, n_layers=4):
        super().__init__()
        layers = [nn.Linear(2,hidden), nn.Tanh()]
        for _ in range(n_layers-1): layers += [nn.Linear(hidden,hidden), nn.Tanh()]
        layers += [nn.Linear(hidden,1)]
        self.net = nn.Sequential(*layers)
        for m in self.modules():
            if isinstance(m,nn.Linear): nn.init.xavier_normal_(m.weight); nn.init.zeros_(m.bias)

    def forward(self, S, t):
        return self.net(torch.cat([S/S_SCALE, t/T_SCALE], dim=1)) * S_SCALE

class BoundNet(nn.Module):
    def __init__(self, K_val, hidden=32, n_layers=3):
        super().__init__()
        self.K_val = K_val
        layers = [nn.Linear(1,hidden), nn.Tanh()]
        for _ in range(n_layers-1): layers += [nn.Linear(hidden,hidden), nn.Tanh()]
        layers += [nn.Linear(hidden,1)]
        self.net = nn.Sequential(*layers)
        for m in self.modules():
            if isinstance(m,nn.Linear): nn.init.xavier_normal_(m.weight); nn.init.zeros_(m.bias)
        self.net[-1].bias.data.fill_(0.0)   # B ≈ K al inicio

    def forward(self, t):
        return self.K_val * (0.7 + 0.3*torch.sigmoid(self.net(t/T_SCALE)))

nn_V = PriceNet(hidden=64, n_layers=4).to(device)
nn_B = BoundNet(K_val=K, hidden=32, n_layers=3).to(device)
print(f'NN_V: {sum(p.numel() for p in nn_V.parameters()):,} params')
print(f'NN_B: {sum(p.numel() for p in nn_B.parameters()):,} params')

"""## Sección 4 — Función de pérdida PINN (7 términos)

$$\mathcal{L} = \underbrace{L_{BS}}_{\lambda=1} + \underbrace{L_{terminal}}_{\lambda=50} + \underbrace{L_{Dirichlet}}_{\lambda=20} + \underbrace{L_{Neumann}}_{\lambda=80} + \underbrace{L_{S_{max}}}_{\lambda=1} + \underbrace{L_{B(T)}}_{\lambda=50} + \underbrace{L_{V\geq0}}_{\lambda=0}$$
"""

def pinn_loss(nn_V, nn_B, S_pde, t_pde, S_ter, t_ter,
              t_dir, t_neu, t_top, t_bt, K, r, sigma, Smax, T, lambdas):
    lam1,lam2,lam3,lam4,lam5,lam6,lam7 = lambdas

    S_pde=S_pde.requires_grad_(True); t_pde=t_pde.requires_grad_(True)
    V=nn_V(S_pde,t_pde)
    V_S,V_t = torch.autograd.grad(V,[S_pde,t_pde],
                                   grad_outputs=torch.ones_like(V),create_graph=True)
    V_SS=torch.autograd.grad(V_S,S_pde,grad_outputs=torch.ones_like(V_S),create_graph=True)[0]
    L1=torch.mean((V_t+0.5*sigma**2*S_pde**2*V_SS+r*S_pde*V_S-r*V)**2)

    L2=torch.mean((nn_V(S_ter,t_ter)-torch.clamp(K-S_ter,min=0))**2)

    B_dir=nn_B(t_dir)
    L3=torch.mean((nn_V(B_dir,t_dir)-(K-B_dir))**2)

    B_neu=nn_B(t_neu).detach().requires_grad_(True)
    dV_dS=torch.autograd.grad(nn_V(B_neu,t_neu),B_neu,
                               grad_outputs=torch.ones_like(B_neu),create_graph=True)[0]
    L4=torch.mean((dV_dS+1)**2)

    L5=torch.mean(nn_V(Smax*torch.ones_like(t_top),t_top)**2)
    L6=torch.mean((nn_B(T*torch.ones_like(t_bt))-K)**2)
    L7=torch.mean(torch.relu(-nn_V(S_pde.detach(),t_pde.detach()))**2)

    loss=lam1*L1+lam2*L2+lam3*L3+lam4*L4+lam5*L5+lam6*L6+lam7*L7
    return loss,{'BS':L1.item(),'terminal':L2.item(),'dirichlet':L3.item(),
                 'neumann':L4.item(),'smax':L5.item(),'BT':L6.item(),'total':loss.item()}
print('Función de pérdida definida — 7 términos')

"""## Sección 5 — Entrenamiento

- **20 000 épocas** con `CosineAnnealingLR` (lr: 1e-3 → 1e-6)
- Muestreo aleatorio de collocación en cada época (2 000 PDE + 500 BC)
- Gradient clipping `max_norm=1.0`
"""

N_EPOCHS = 20000; LR = 1e-3; N_PDE = 2000; N_BC = 500
LAMBDAS = [1.0, 50.0, 20.0, 80.0, 1.0, 50.0, 0.0]

optimizer = optim.Adam(list(nn_V.parameters())+list(nn_B.parameters()), lr=LR)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=N_EPOCHS, eta_min=1e-6)

hist_total=[]; hist_comp={k:[] for k in ['BS','terminal','dirichlet','neumann','smax','BT']}

def sample_points(N_PDE, N_BC):
    def col(n,lo,hi): return torch.FloatTensor(n,1).uniform_(lo,hi).to(device)
    return (col(N_PDE,0.01*Smax,0.99*Smax), col(N_PDE,0,T),
            col(N_BC,0.01*Smax,0.99*Smax),  T*torch.ones(N_BC,1).to(device),
            col(N_BC,0,T), col(N_BC,0,T), col(N_BC,0,T),
            T*torch.ones(N_BC//4,1).to(device))

print(f'Entrenando {N_EPOCHS} épocas...')
for epoch in range(1, N_EPOCHS+1):
    optimizer.zero_grad()
    pts  = sample_points(N_PDE, N_BC)
    loss,comp = pinn_loss(nn_V,nn_B,*pts,K=K,r=r,sigma=sigma,Smax=Smax,T=T,lambdas=LAMBDAS)
    loss.backward()
    torch.nn.utils.clip_grad_norm_(list(nn_V.parameters())+list(nn_B.parameters()),1.0)
    optimizer.step(); scheduler.step()
    hist_total.append(comp['total'])
    for k in hist_comp: hist_comp[k].append(comp[k])
    if epoch%1000==0 or epoch==1:
        print(f'Época {epoch:5d} | Loss:{comp["total"]:.3e} | BS:{comp["BS"]:.2e} '
              f'| Dir:{comp["dirichlet"]:.2e} | Neu:{comp["neumann"]:.2e} '
              f'| LR:{optimizer.param_groups[0]["lr"]:.1e}')
print('Entrenamiento completado.')

"""## Sección 6 — Resultados y comparación con árbol binomial (N=1000)"""

nn_V.eval(); nn_B.eval()

with torch.no_grad():
    precio_pinn = float(nn_V(torch.tensor([[S0]],dtype=torch.float32).to(device),
                             torch.tensor([[0.0]],dtype=torch.float32).to(device)).item())
    t_grid   = np.linspace(0,T,300)
    t_grid_t = torch.tensor(t_grid.reshape(-1,1),dtype=torch.float32).to(device)
    B_pinn   = nn_B(t_grid_t).cpu().numpy().flatten()
    S_range  = np.linspace(0.8*K,1.2*K,100)
    t_vals   = [0.0, T/4, T/2, 3*T/4, T]
    curvas   = {}
    for tv in t_vals:
        S_t=torch.tensor(S_range.reshape(-1,1),dtype=torch.float32).to(device)
        t_t=tv*torch.ones(len(S_range),1,dtype=torch.float32).to(device)
        vp=nn_V(S_t,t_t).cpu().numpy().flatten()
        curvas[tv]=np.maximum(vp,np.maximum(K-S_range,0))

mae  = abs(precio_pinn-precio_binomial)
mape = mae/precio_binomial*100
mae_boundary = np.mean(np.abs(B_pinn-np.interp(t_grid,t_bin,B_bin)))

print(f'Precio PINN:     ${precio_pinn:.4f}')
print(f'Precio Binomial: ${precio_binomial:.4f}  (N=1000)')
print(f'MAE: ${mae:.4f}   MAPE: {mape:.2f}%')
print(f'B(0) PINN: ${B_pinn[0]:.2f}  |  B(0) Binomial: ${B_bin[0]:.2f}')
print(f'B(T) PINN: ${B_pinn[-1]:.2f}  (debe ≈ K=${K})')
print(f'MAE frontera: ${mae_boundary:.4f}')

fig=plt.figure(figsize=(14,10)); gs=gridspec.GridSpec(2,2,hspace=0.4,wspace=0.35)

ax1=fig.add_subplot(gs[0,0])
ax1.plot(t_grid,B_pinn,'steelblue',lw=2.5,label='PINN $B(t)$')
ax1.plot(t_bin,B_bin,'darkorange',lw=2,ls='--',label='Binomial $B(t)$')
ax1.axhline(K,color='gray',ls='--',lw=1.2,label=f'K=${K}')
ax1.axhline(S0,color='green',ls=':',lw=1.2,label=f'S₀=${S0:.0f}')
ax1.fill_between(t_grid,B_pinn,K,alpha=.10,color='steelblue')
ax1.fill_between(t_grid,0.88*K,B_pinn,alpha=.10,color='red')
ax1.text(T*.4,(np.mean(B_pinn)+K)/2,'Holding Region',fontsize=10,ha='center',color='steelblue',fontweight='bold')
ax1.text(T*.4,B_pinn[0]*.965,'Exercise Region',fontsize=10,ha='center',color='red',fontweight='bold')
ax1.set(xlabel='Tiempo $t$ (años)',ylabel='Precio SPY ($)',title='Frontera Óptima $B(t)$',
        ylim=(0.88*K,1.04*K),xlim=(0,T)); ax1.legend(fontsize=9); ax1.grid(alpha=.3)

ax2=fig.add_subplot(gs[0,1])
for (tv,curva),col in zip(curvas.items(),['#003f5c','#58508d','#bc5090','#ff6361','#ffa600']):
    dias=int(tv*365)
    ax2.plot(S_range,curva,color=col,lw=2,
             label='t=0 (hoy)' if tv==0 else 't=T (venc.)' if tv==T else f't={dias}d')
ax2.plot(S_range,np.maximum(K-S_range,0),'k--',lw=1.5,label='Payoff')
ax2.axvline(S0,color='green',ls=':',lw=1.5); ax2.axvline(K,color='gray',ls='--',lw=1)
ax2.set(xlabel='S ($)',ylabel='V ($)',title='Curvas $V(S,t)$ — PINN',xlim=(0.8*K,1.2*K))
ax2.legend(fontsize=9); ax2.grid(alpha=.3)

ax3=fig.add_subplot(gs[1,0])
S_eval=np.linspace(0.85*K,1.15*K,40)
V_bin_eval=[american_put_binomial(s,K,r,sigma,T,N=1000) for s in S_eval]
V_pinn_eval=np.interp(S_eval,S_range,curvas[0.0])
V_bs_eval  =[bs_european_put(s,K,r,sigma,T) for s in S_eval]
ax3.plot(S_eval,V_pinn_eval,'steelblue',lw=2.5,marker='o',ms=3,label='PINN')
ax3.plot(S_eval,V_bin_eval,'darkorange',lw=2,ls='--',marker='s',ms=3,label='Binomial Am.')
ax3.plot(S_eval,V_bs_eval,'#D2A8FF',lw=1.8,label='BS Europeo')
ax3.plot(S_range,np.maximum(K-S_range,0),'k--',lw=1.2,label='Payoff')
ax3.axvline(S0,color='green',ls=':',lw=1.5)
ax3.set(xlabel='S ($)',ylabel='V ($)',title='PINN vs Binomial vs BS  ($t=0$)')
ax3.legend(fontsize=9); ax3.grid(alpha=.3)

ax4=fig.add_subplot(gs[1,1])
ax4.semilogy(hist_total,'black',lw=1.5,label='Total')
for k,col in {'BS':'steelblue','terminal':'darkorange','dirichlet':'green','neumann':'red'}.items():
    ax4.semilogy(hist_comp[k],color=col,lw=1,alpha=.7,label=k)
ax4.set(xlabel='Época',ylabel='Pérdida (log)',title='Convergencia PINN')
ax4.legend(fontsize=9); ax4.grid(alpha=.3)

plt.suptitle(f'PINN — Put Americana SPY | K=${K} | σ={sigma*100:.2f}% | T=60d',fontsize=13,y=1.01)
plt.tight_layout(); plt.show()

"""## Sección 7 — Interpretación financiera"""

payoff_real=max(K-S_final_real,0); ganancia=payoff_real-precio_pinn
print(f'Prima PINN:     ${precio_pinn:.4f}  |  Prima Binomial: ${precio_binomial:.4f}')
print(f'SPY al venc:    ${S_final_real:.2f}  ({((S_final_real/S0)-1)*100:+.2f}%)')
print(f'Payoff real:    ${payoff_real:.2f}')
if payoff_real==0:
    print(f'→ SPY subió — put expiró sin valor. Pérdida: ${precio_pinn:.4f} (prima)')
else:
    print(f'→ Ganancia neta: ${ganancia:.4f}')
print(f'B(0) PINN=${B_pinn[0]:.2f} | B(0) Binomial=${B_bin[0]:.2f}')
print(f'MAE precio: ${mae:.4f} ({mape:.2f}%)  |  MAE B(t): ${mae_boundary:.4f}')

"""## Sección 8A — PINN vs Binomial vs Black-Scholes a lo largo del camino real

Se evalúa $V(S_{real}(t), t)$ para cada día observado del SPY durante el contrato,
comparando la PINN contra la referencia binomial americana (N=1000) y la put europea BS.
"""

n_dias_real = len(precios_reales)
t_reales_8  = np.linspace(0, T, n_dias_real)
tau_reales  = T - t_reales_8           # tiempo a vencimiento
t_norm_plot = t_reales_8 / T           # eje x ∈ [0,1]

print('Calculando precios a lo largo del camino real (N=1000 para binomial)...')
V_binom_path = np.array([american_put_binomial(s,K,r,sigma,max(tau,1e-6),N=1000)
                          for s,tau in zip(precios_reales,tau_reales)])
V_bs_path    = np.array([bs_european_put(s,K,r,sigma,max(tau,1e-6))
                          for s,tau in zip(precios_reales,tau_reales)])
V_pinn_path  = []
nn_V.eval()
with torch.no_grad():
    for s,t in zip(precios_reales,t_reales_8):
        v=float(nn_V(torch.tensor([[s]],dtype=torch.float32).to(device),
                     torch.tensor([[t]],dtype=torch.float32).to(device)).item())
        V_pinn_path.append(max(v,max(K-s,0)))
V_pinn_path=np.array(V_pinn_path)

with np.errstate(divide='ignore',invalid='ignore'):
    err_pinn=np.where(V_binom_path>0.5,np.abs(V_pinn_path-V_binom_path)/V_binom_path*100,0)
    err_bs  =np.where(V_binom_path>0.5,np.abs(V_bs_path  -V_binom_path)/V_binom_path*100,0)

fig,(ax_a,ax_b)=plt.subplots(1,2,figsize=(16,6))
fig.suptitle('Predicciones de Precio y Errores Relativos — SPY 2025\n'
             '(Referencia: Árbol Binomial Americano N=1000)',fontsize=13,fontweight='bold')

ax_a.plot(t_norm_plot,V_binom_path,'-', color='#3FB950',lw=2.5,marker='^',ms=3,label='Americana Binomial (referencia)')
ax_a.plot(t_norm_plot,V_pinn_path, '--',color='#58A6FF',lw=2,  marker='o',ms=3,label='PINN')
ax_a.plot(t_norm_plot,V_bs_path,   '-', color='#D2A8FF',lw=1.8,            label='Europea Black-Scholes')
ax_a.set(xlabel='t (tiempo normalizado)',ylabel='Precio de la opción (USD)',
         title='(a) Precio de la Put vs tiempo de mercado',xlim=(0,1)); ax_a.set_ylim(bottom=0)
ax_a.legend(fontsize=10); ax_a.grid(alpha=.3)

ax_b.axhline(0,color='#3FB950',lw=1.5,label='Binomial vs referencia = 0%')
ax_b.plot(t_norm_plot,np.clip(err_pinn,0,100),'--',color='#58A6FF',lw=1.8,marker='o',ms=3,label='Error PINN')
ax_b.plot(t_norm_plot,np.clip(err_bs,  0,100),'-', color='#D2A8FF',lw=1.5,              label='Error BS europeo')
ax_b.set(xlabel='t (tiempo normalizado)',ylabel='Error relativo (%)',
         title='(b) Error relativo contra binomial americano',xlim=(0,1),ylim=(0,105))
ax_b.legend(fontsize=10); ax_b.grid(alpha=.3)

plt.tight_layout(); plt.show()
print(f'MAE PINN vs Binomial (camino real): ${np.mean(np.abs(V_pinn_path-V_binom_path)):.4f}')
print(f'MAPE PINN vs Binomial (camino real): {np.mean(err_pinn[V_binom_path>0.5]):.2f}%')

"""## Sección 8B — Superficie 3D: PINN vs Árbol Binomial

Superficie $V(S, t)$ sobre la grilla $S \in [0.5K,\, 1.4K]$, $t \in [0, T]$.
"""

print('Calculando superficie 3D...')
N_S3d=40; N_t3d=30
S_3d=np.linspace(0.5*K,1.4*K,N_S3d); t_3d=np.linspace(0,T,N_t3d)
SS,TT=np.meshgrid(S_3d,t_3d)

V_pinn_3d=np.zeros_like(SS)
nn_V.eval()
with torch.no_grad():
    for i,tv in enumerate(t_3d):
        S_b=torch.tensor(S_3d.reshape(-1,1),dtype=torch.float32).to(device)
        t_b=tv*torch.ones(N_S3d,1,dtype=torch.float32).to(device)
        vr =nn_V(S_b,t_b).cpu().numpy().flatten()
        V_pinn_3d[i,:]=np.maximum(vr,np.maximum(K-S_3d,0))

V_binom_3d=np.zeros_like(SS)
for i,tv in enumerate(t_3d):
    tau_v=max(T-tv,1e-6)
    for j,sv in enumerate(S_3d):
        V_binom_3d[i,j]=american_put_binomial(sv,K,r,sigma,tau_v,N=300)

vmin=0; vmax=max(V_pinn_3d.max(),V_binom_3d.max()); cmap='RdYlBu_r'
fig3d=plt.figure(figsize=(18,7))
fig3d.suptitle('Superficie 3D del Precio de la Put Americana',fontsize=14,fontweight='bold')

ax1=fig3d.add_subplot(121,projection='3d')
s1=ax1.plot_surface(SS,TT,V_pinn_3d,cmap=cmap,vmin=vmin,vmax=vmax,alpha=.92,linewidth=0)
ax1.set(xlabel='S (Precio SPY)',ylabel='t (tiempo)',zlabel='V (USD)',title='PINN')
fig3d.colorbar(s1,ax=ax1,shrink=.5,label='V (USD)')

ax2=fig3d.add_subplot(122,projection='3d')
s2=ax2.plot_surface(SS,TT,V_binom_3d,cmap=cmap,vmin=vmin,vmax=vmax,alpha=.92,linewidth=0)
ax2.set(xlabel='S (Precio SPY)',ylabel='t (tiempo)',zlabel='V (USD)',title='Árbol Binomial')
fig3d.colorbar(s2,ax=ax2,shrink=.5,label='V (USD)')

plt.tight_layout(); plt.show()
print('Superficie 3D lista.')

"""## Sección 8C — Validación con datos reales del SPY"""

fechas=fechas_reales; precios=precios_reales
n_dias=len(precios); t_reales=np.linspace(0,T,n_dias)

nn_B.eval()
with torch.no_grad():
    B_en_dias=nn_B(torch.tensor(t_reales.reshape(-1,1),dtype=torch.float32).to(device)).cpu().numpy().flatten()

debio_ejercer=precios<B_en_dias; dias_ej=np.where(debio_ejercer)[0]; hubo_cruce=len(dias_ej)>0
if hubo_cruce:
    dia_opt=dias_ej[0]; fecha_opt=fechas[dia_opt]; S_opt=precios[dia_opt]; pay_opt=max(K-S_opt,0)
else:
    dia_opt=fecha_opt=S_opt=None; pay_opt=0

fig,(ax1,ax2)=plt.subplots(2,1,figsize=(11,9),gridspec_kw={'hspace':.45})
ax1.plot(t_reales,precios,'black',lw=2,label='SPY (real)',zorder=5)
ax1.plot(t_grid,B_pinn,'steelblue',lw=2.5,label='$B(t)$ PINN',zorder=4)
ax1.plot(t_bin,B_bin,'darkorange',lw=2,ls='--',label='$B(t)$ Binomial',zorder=3)
ax1.axhline(K,color='gray',ls='--',lw=1.2,label=f'K=${K}')
ax1.fill_between(t_grid,B_pinn,K,alpha=.08,color='steelblue')
ax1.fill_between(t_grid,0.85*K,B_pinn,alpha=.08,color='red')
if hubo_cruce:
    ax1.scatter(t_reales[debio_ejercer],precios[debio_ejercer],color='red',s=30,zorder=6,label='Exercise Region')
    ax1.axvline(t_reales[dia_opt],color='red',ls=':',lw=1.5,label=f'1er cruce: {str(fecha_opt)[:10]}')
    ax1.scatter([t_reales[dia_opt]],[S_opt],color='red',s=150,zorder=7,marker='*')
else:
    ax1.text(T*.35,(np.mean(B_pinn)+K)/1.97,
             'El SPY nunca cruzó B(t)\n→ No convenía ejercer anticipadamente',
             fontsize=10,ha='center',bbox=dict(boxstyle='round',facecolor='lightyellow',alpha=.8))
ax1.set(xlabel='t (años)',ylabel='Precio SPY ($)',
        title=f'Camino Real del SPY vs Frontera $B(t)$  ({FECHA_INICIO_CONTRATO} → {FECHA_FIN_CONTRATO})',
        xlim=(0,T),ylim=(0.85*K,max(precios)*1.05))
ax1.legend(fontsize=9,loc='upper left'); ax1.grid(alpha=.3)

nn_V.eval()
V_dias=[]
with torch.no_grad():
    for s,t in zip(precios,t_reales):
        v=float(nn_V(torch.tensor([[s]],dtype=torch.float32).to(device),
                     torch.tensor([[t]],dtype=torch.float32).to(device)).item())
        V_dias.append(max(v,max(K-s,0)))
V_dias=np.array(V_dias)

ax2.plot(t_reales,V_dias,'steelblue',lw=2,label='Valor PINN $V(S_{real},t)$')
ax2.plot(t_reales,np.maximum(K-precios,0),'k--',lw=1.5,label='Valor intrínseco')
ax2.axhline(precio_pinn,color='green',ls=':',lw=1.5,label=f'Prima: ${precio_pinn:.2f}')
if hubo_cruce:
    ax2.axvline(t_reales[dia_opt],color='red',ls=':',lw=1.5)
    ax2.scatter([t_reales[dia_opt]],[V_dias[dia_opt]],color='red',s=150,marker='*')
ax2.set(xlabel='t (años)',ylabel='Valor put ($)',
        title='Valor de la Put a lo largo del Contrato',xlim=(0,T))
ax2.legend(fontsize=9); ax2.grid(alpha=.3)

plt.suptitle(f'Validación con Datos Reales — SPY K=${K} σ={sigma*100:.2f}% T=60d',fontsize=13,y=1.01)
plt.tight_layout(); plt.show()

print('='*60)
print('RESUMEN FINAL')
print('='*60)
print(f'Prima PINN: ${precio_pinn:.4f}  |  Prima Binomial: ${precio_binomial:.4f}')
print(f'S₀=${S0:.2f} → S_T=${S_final_real:.2f}  ({((S_final_real/S0)-1)*100:+.2f}%)')
if hubo_cruce:
    print(f'✓ Cruce el {str(fecha_opt)[:10]} | Payoff: ${pay_opt:.4f} | Ganancia: ${pay_opt-precio_pinn:.4f}')
else:
    print('✗ El SPY nunca cruzó B(t) → put expiró sin valor')
    print(f'  Pérdida: ${precio_pinn:.4f} (prima pagada)')
print(f'MAE precio: ${mae:.4f} ({mape:.2f}%)  |  MAE B(t): ${mae_boundary:.4f}')
print('='*60)

"""## Sección 9 — Guardar pesos del modelo"""

torch.save({
    'nn_V_state': nn_V.state_dict(),
    'nn_B_state': nn_B.state_dict(),
    'params': {'K':K,'r':r,'sigma':sigma,'T':T,'S0':S0,'S_SCALE':S_SCALE,'T_SCALE':T_SCALE},
    'hist_total': hist_total, 'hist_comp': hist_comp,
    'mae':mae, 'mape':mape, 'precio_pinn':precio_pinn, 'precio_binomial':precio_binomial,
}, 'pinn_spy_put_weights.pt')
print('Modelo guardado: pinn_spy_put_weights.pt')
print('Para cargar: checkpoint = torch.load("pinn_spy_put_weights.pt")')
print('             nn_V.load_state_dict(checkpoint["nn_V_state"])')
print('             nn_B.load_state_dict(checkpoint["nn_B_state"])')